- conf/default.cfg
- oioswift/hashedcontainer.py
- setup.py
Configuration change: "sds_namespace", "sds_proxy_url" and
"sds_default_account" are exepected in the DEFAULT section and can be
overriden in the section of each filter (that require them).
> autocontainer "flat ns" implementation

- conf/default.cfg
- oioswift/proxy/controllers/account.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- setup.py
various fixes around error handling and metadata handling
> update for swift 2.10 (min version required)

- conf/default.cfg
- oioswift/hashedcontainer.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- oioswift/server.py
- tests/unit/controllers/test_obj.py
Add conf to select the auto storage policy in the form of
auto_storage_policies=SINGLE,EC:10000000
It is only use when there is no storage policy define for the container
(Policy-0)
> Controllers: Add a storage policy depending of the size

- oioswift/proxy/controllers/account.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- tests/unit/__init__.py
- tests/unit/controllers/test_account.py
- tests/unit/controllers/test_obj.py
> Use x-trans-id as openio-sds request id

- oioswift/proxy/controllers/obj.py
- tests/unit/controllers/test_obj.py
> Add tests for truncated inputs

- .gitmodules
- .travis.yml
- oioswift/common/middleware/versioned_writes.py
- tests/unit/common/middleware/test_versioned_writes.py
At least target up-to-date stable dependencies.
> Fix indirect dependencies

- oioswift/common/middleware/versioned_writes.py
When intercepting listing requests directed towards versioning
container, do not list the latest version of each object: it is supposed
to appear only in the main container.
> versioned_writes: do not list the latest version

- oioswift/common/middleware/container_hierarchy.py
When distcp copy data onto S3 conainer, following stuff happens:
creating empty objects (dir1/, dir1/dir2/, ...) to simulate directory,
upload data on /.attempt and then remove
launch a copy /.attempt to /dir/dir2/.../object
and finally remove empty objects dir1/dir2/..., dir1/dir2/, dir1/
This last step breaks listing with container_hierarchy enabled.
This commit silently drops removing object with trailing /
> [WIP] container_hierarchy: add a workaround for distcp

- .gitmodules
- .travis.yml
- oioswift/common/middleware/container_hierarchy.py
- test-requirements.txt
- tests/functional/run_tests.sh
- tests/functional/s3_container_hierarchy.sh
- tests/functional/s3_container_hierarchy_v2.sh
- tests/functional/simple.cfg
Add more functionals tests
Add flake8 step
Add coverage
Add swift3 in thirdparty
Add script to launch oioswift with a simple pipeline to launch functional tests with swift3 (requires a SDS listening on 127.0.0.1 proxy)
TODO:
Launch functional tests
Fix configuration with current user
Fix HEAD on placeholder
> Implement new functional tests, prepare better CI

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/s3_container_hierarchy.sh
> container_hierarchy: fix prefixed recursive listing, factorize code

- conf/default.cfg
* Better timeout values
* Explained storage policies
* Fixed default values
> Documentation effort in the default configuration

- oioswift/common/middleware/container_hierarchy.py
- oioswift/common/middleware/versioned_writes.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- oioswift/utils.py
- tests/unit/controllers/test_obj.py
Related to open-io/oio-sds#555
> Implement If-None-Match

- oioswift/common/middleware/container_hierarchy.py
This commit fix paginated listing:
- the marker parameter was not used
- the limit was not used, even using pagesize of 1000,
10000 entries was extracted.
- the result of listing was not sorted and a previous entries
were reused instead of last one
Please note that end_marker is not managed yet
> container_hierarchy: fix paginated listing

- .travis.yml
- conf/s3_container_hierarchy.cfg
- oioswift/common/middleware/container_hierarchy.py
- test-requirements.txt
- tests/functional/common.sh
- tests/functional/run_ns_wide_versioning_tests.sh
- tests/functional/run_s3_tests.sh
- tests/functional/s3_container_hierarchy_v2.sh
Enable S3 test with `container_hierarchy` middleware
Fix an issue with listing limit inside `container_hierarchy` 
Coverage is not yet working for tests launched through `runserver.py`
> Enable S3 testsuite

- conf/default.cfg
- oioswift/common/middleware/crypto/crypto_utils.py
- oioswift/common/middleware/crypto/decrypter.py
- oioswift/common/middleware/crypto/keymaster.py
- oioswift/common/request_helpers.py
- oioswift/server.py
- tests/functional/custom-encryption-tests.sh
First version of a script to test encryption
> Allow encryption key change, improve tests

- oioswift/proxy/controllers/obj.py
- tests/unit/controllers/test_obj.py
It will use new API object_create_ext if available otherwise
it will fallback on a extra call with object_get_properties.
> Expose object version in response

- oioswift/common/middleware/versioned_writes.py
- oioswift/proxy/controllers/obj.py
- tests/functional/s3-versioning.sh
Version ID was not taken into account when setting object metadata. It was also impossible to specify the source version when creating an object link. This has been fixed.
Also, do not clear all properties when a POST request comes from swift3.
Jira: OS-312
> Several fixes around versioning and properties

- oioswift/common/middleware/autocontainerbase.py
- oioswift/common/middleware/verb_acl.py
When using autocontainer, hashedcontainer or regexcontainer,
and handling a 'GET /' request, spit out the list of all containers.
Jira: OS-313
> Improve verb_acl, handle service requests with autocontainer middleware

- oioswift/common/middleware/container_hierarchy.py
- tests/unit/common/middleware/test_container_hierarchy.py
Do not scan the key set, we know which key we want.
Also make things a little more readable.
> CH: do not scan keys, get to the point

- tests/functional/s3-multipart.sh
It requires https://github.com/open-io/swift3/pull/58
> tests: add MPU test for ETag

- oioswift/common/middleware/container_hierarchy.py
> Do not log "failed to create key" when the key exists

- oioswift/common/middleware/container_hierarchy.py
- oioswift/proxy/controllers/container.py
- tests/functional/run-s3-tests.sh
- tests/functional/s3-marker.sh
- tests/functional/s3-versioning-container-hierarchy.sh
- tests/functional/s3_container_hierarchy_v2.sh
- tests/unit/common/middleware/test_container_hierarchy.py
- tools/conversion_hierarchy_v3.lua
This new format use zset to make listing faster
> CH: Add new keys format

- oioswift/common/middleware/container_hierarchy.py
Start at Prefix if set
Stop if keys doesn't match anymore prefix
Turn off the pattern matching
> CHv3: few optims

- conf/default.cfg
- oioswift/common/middleware/container_hierarchy.py
> CH: Allow to set various Redis sentinel parameters

- .travis.yml
- bin/oioswift-proxy-server
- conf/default.cfg
- conf/hashed-containers.cfg
- conf/s3-container-hierarchy.cfg
- conf/s3-default.cfg
- conf/s3-fastcopy.cfg
- conf/s3-versioning-custom-encryption.cfg
- conf/s3-versioning-encryption.cfg
- conf/swift-flatns-skip-metadata.cfg
- oioswift/common/middleware/slo.py
- oioswift/common/wsgi.py
- oioswift/proxy/controllers/account.py
- oioswift/proxy/controllers/container.py
- setup.py
Check MPU with single listing instead of several HEADs
Jira: OS-480
> SLO: Check MPU with single listing instead of several HEADs

- .gitmodules
- .travis.yml
- conf/iam_rules.json
- conf/s3-container-hierarchy.cfg
- conf/s3-fastcopy.cfg
- conf/s3-iam.cfg.in
- conf/s3-versioning-custom-encryption.cfg
- conf/s3-versioning-encryption.cfg
- conf/swift-flatns-skip-metadata.cfg
- oioswift/common/middleware/autocontainerbase.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- oioswift/utils.py
- tests/functional/common.sh
- tests/functional/run-iam-tests.sh
- tests/functional/run-s3-tests.sh
- tests/functional/s3-iam.sh
- tests/functional/s3-versioning-container-hierarchy.sh
- tests/functional/s3_container_hierarchy_v2.sh
- tests/unit/controllers/test_obj.py
Implement tests with IAM. Also, save extra metadata in container shards.
> Implement tests with IAM

- oioswift/common/middleware/slo.py
- oioswift/proxy/controllers/obj.py
- tests/functional/s3-multipart.sh
Linked: https://github.com/open-io/swift3/pull/87
Jira: OS-556
> Allow to download the MPU object if the etag matches

- oioswift/proxy/controllers/account.py
Since 5.3.0, SDS now have an aggregated view of bucket.
This PR will allow to reuse this view to list bucket.
Note: each bucket should have at least one write or delete operation
since 5.3.0 update to be available into this list.
If method is not available, the old method will be called.
> Use new SDS API to list buckets
