open-io/oio-swift

- oioswift/autocontainer.py
- oioswift/hashedcontainer.py
Previously the leading '/' was not included in object names but included
while computing autocontainer name.
> Do not include leading '/' in object names

- conf/default.cfg
- oioswift/server.py
This changes a little the configuration file: SDS options are now
all prefixed with "sds_".
> Allow setting connection pools options

- oioswift/proxy/controllers/obj.py
- oioswift/server.py
Since property values are not urldecoded during PUT, they should
not be urlencoded during HEAD and GET.
> Remove an unwanted urlencode of properties in HEAD and GET

- oioswift/proxy/controllers/obj.py
- tests/unit/__init__.py
- tests/unit/controllers/test_account.py
- tests/unit/controllers/test_container.py
- tests/unit/controllers/test_obj.py
Remove some tests which are no more relevant (COPY is handled by a
dedicated middleware, swift.log_info is never set).
> Fix unit tests

- oioswift/proxy/controllers/account.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- oioswift/utils.py
Catch error 503 to return `HTTPServiceUnavailable` with` Retry-After` in the header.
See [oio-sds#1104](https://github.com/open-io/oio-sds/pull/1104)
> controllers: Manage error 503

- conf/default.cfg
- oioswift/common/middleware/autocontainerbase.py
- oioswift/common/middleware/regexcontainer.py
Now, the regexcontainer middleware is able to loop on patterns if
the one that matches triggers a 404 error.
> regexcontainer: add stop_at_first_match option

- oioswift/common/middleware/container_hierarchy.py
- oioswift/common/middleware/copy.py
- oioswift/proxy/controllers/obj.py
- setup.py
Fix several issues with listings
Allow fast copy only with single object.
For FastCopy, it is required to add copy in pipeline before DLO and SLO
and set in configuration file:
```
[filter:copy]
use = egg:oioswift#copy
```
> Fix listings and allow FastCopy

- oioswift/common/middleware/copy.py
- oioswift/proxy/controllers/obj.py
To reproduce it:
$ dd if=/dev/zero of=bigfile bs=1M count=20M
$ aws s3 cp bigfile s3://bucket
$ aws s3api copy-object --bucket bucket --copy-source bucket/bigfile --key plain_object
Error message to impossible case in proxy/controller/obj.py has also
been updated to be more explicit.
> fastcopy: fix SLO as source and plain objet as target

- .travis.yml
- oioswift/common/middleware/autocontainerbase.py
This commit fix the MPU fonctionality:
- when a MPU is complete, it check every part
The autocontainer now fix listing with prefix (prefix itself is not
updated but prefix path is used when resolving container name)
- When manifest is send by swift3, autocontainerbase got an iterator
instead of a proper status, headers, ... We force call to reiterate
to resolve it.
> Autocontainer: fix MPU complete

- oioswift/common/middleware/autocontainerbase.py
- oioswift/common/middleware/copy.py
Fastcopy was not compatible with Autocontainer, new header was
unprocessed.
When a copy is done with UTF-8 characters, copy failed with double
quote issue.
> copy: fix autocontainer and utf8

- conf/default.cfg
- oioswift/proxy/controllers/obj.py
- oioswift/server.py
It requires an updated version of OIO-SDS that exposes this parameter,
otherwise parameter will be ignored with a warning.
> Expose parameter to control container autocreate

- oioswift/common/middleware/hashedcontainer.py
Fix `multiple values for keyword argument` error
> hashedcontainer: fix parameters

- .codecov.yml
- .travis.yml
- conf/default.cfg
- oioswift/proxy/controllers/obj.py
- oioswift/server.py
- tests/functional/run-ns-wide-versioning-tests.sh
- tests/functional/run-s3-tests.sh
- tests/functional/s3-multipart.sh
- tests/unit/controllers/test_obj.py
- tests/unit/run_extra_unit_tests.sh
- tests/unit/run_unit_tests.sh
When a static large object manifest is overwritten, swift's default behavior is to keep the parts, in case another manifest references them. It is the container owner's responsability to delete them. oioswift changes this behavior and deletes the parts by default. To re-establish the default behavior, toggle `delete_slo_parts` to false.
> Delete parts when overwriting a SLO

- oioswift/common/middleware/versioned_writes.py
- tests/unit/common/middleware/test_versioned_writes.py
- tests/unit/run_extra_unit_tests.sh
- tests/unit/run_unit_tests.sh
When returning object versions, and the request specifies a delimiter, do not return object prefixes.
The upper level usually sends two requests: one for the latest version of each object, one for all previous versions of all objects. Now only the first will return object prefixes.
Jira: OS-211
> versioned_writes: discard object prefixes from listings

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/s3_container_hierarchy_v2.sh
- tests/unit/common/middleware/test_container_hierarchy.py
When an intermediary container is created with space, it is used on container name.
But when listing this container, the space was first converted to `+` with `quote_plus` and then again converted later to `%2B` in `urllib3.request` before sending request.
JIRA: OS-216
> CH: allow listing containers with space

- oioswift/common/middleware/container_hierarchy.py
- tests/unit/common/middleware/test_container_hierarchy.py
This commit will allow to store all parts of a multipart upload in the same container as regular objects of the same directory.
Previously, a MultiPartUpload to `/bucket/dir/dir2/object` was storing its parts in `/bucket/dir/dir2/object/uploadid/` container with object names 1, 2, 3...
With this fix, parts will be stored in `/bucket/dir/dir2/` and named like `object/uploadid/1`, `object/uploadid/2`...
> CH: fix container name used for MPU

- oioswift/common/middleware/container_hierarchy.py
The `e8634f7f5e02690548b5e8f12ae2513d3e586d99` changes on Container Hierarchy on new version.
The test was here but hidden in all logs
> Container Hierarchy: save bucket name in metadata

- oioswift/common/middleware/container_hierarchy.py
By default, scan_iter use `count` with 10 that make lot of
requests between gateway and redis that impact listing performance.
> ContainerHierarchy: improve redis scan

- oioswift/proxy/controllers/obj.py
- tests/functional/s3-versioning.sh
Read metadata after uploading an object works on small DB but may fails
on largest ones since read operations are done on SLAVE and may not yet
be synchronized.
> Rely only on new API to expose versioning

- oioswift/proxy/controllers/obj.py
- oioswift/server.py
- oioswift/utils.py
- tests/unit/controllers/test_obj.py
If check_quorum flag is set in configuration then a HEAD operation
will occurs on each chunks to verify if quorum is reached for each
metachunk.
Warning, this flag will have impact on rawx server.
> Check object state on HEAD

- oioswift/proxy/controllers/obj.py
- oioswift/utils.py
- runserver.py
- tests/unit/controllers/test_obj.py
These exceptions are raised when some chunks are not available (but not
necessarily lost). Proper usage of ServiceUnavailable exceptions has
been implemented in oio-sds 4.2.7.
Jira: OS-263
> Trap ServiceUnavailable exceptions

- test-requirements.txt
- tests/functional/common.sh
- tests/functional/run-s3-tests.sh
- tests/functional/s3-s3cmd.sh
The test added exhibits issue resolved with https://github.com/open-io/swift3/pull/49
where content-type of ACL put object is misused and replace
object content-type.
> tests: add test using s3cmd

- oioswift/common/middleware/container_hierarchy.py
- oioswift/proxy/controllers/container.py
- tests/functional/s3_container_hierarchy_v2.sh
Some clients use `:` in PATH to mimic Windows behavior or use them as separator to custom versioning like Cloud Berry
Fixes OS-308
> ContainerHierarchy: fix listing with : in object

- .travis.yml
- tests/functional/common.sh
`oio-sds` requires requires minimum version `2.46` of Glib but trusty only has `2.40`
> CI: bump travis configuration to Ubuntu Xenial

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/s3_container_hierarchy_v2.sh
Catch versioning introduced by CloudBerry Backup to avoid one container per version and object
Fixes OS-323
> CH: add specific check for CloudBerry versioning

- .travis.yml
- conf/default.cfg
- conf/swift-flatns-skip-metadata.cfg
- oioswift/common/middleware/autocontainerbase.py
- oioswift/common/middleware/hashedcontainer.py
- tests/functional/common.sh
- tests/functional/run-swift-tests.sh
- tests/functional/swift-skip-metadata.sh
Depending on how the gateway is used, it may make sense to skip `account` and `container` metadata retrievals (no quota and no authentication in the pipeline).
> HashedContainer: allow skipping metadata retrievals

- oioswift/common/middleware/container_hierarchy.py
- oioswift/proxy/controllers/container.py
After removing an object, the listing to check removal of key will now
be forced to occurs on master to avoid unsynchronized use of slave.
It requires https://github.com/open-io/oio-sds/pull/1677
Fixes OS-331
> ContainerHierarchy: force listing on master

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/common.sh
- tests/functional/run-encryption-tests.sh
- tests/functional/run-ns-wide-versioning-tests.sh
- tests/functional/run-s3-tests.sh
- tests/functional/run-swift-tests.sh
- tests/functional/s3-marker.sh
- tests/unit/common/middleware/test_container_hierarchy.py
By default, all REDIS operations occurred on `master`: since the most used operations is `READ` for listing request, now theses operations will be done on `slave`.
It could be managed by a flag if a customer prefer consistency over performance.
This PR also fix invalid marker:
- marker without / was not managed
- marker with / always ignored root container that led to ignore objects stored in it
> CH: Redis improvement and marker fixes

- conf/s3-container-hierarchy-key-v2.cfg
- oioswift/common/middleware/container_hierarchy.py
- tests/functional/s3_container_hierarchy_v2.sh
- tests/unit/common/middleware/test_container_hierarchy.py
This PR add fixes and enhancements regarding Container Hierarchy and how fake directories are managed.
Previously, the "directory" object was managed by listing, `DELETE` and `PUT`.
Any `GET` or `HEAD` requests were still forwarded to `sds`:
Now, `GET` or `HEAD` request with "directory" object will check in `redis` to response 200 or 404.
Any requests `HEAD` or `GET` on object (normal or directory object without trailing /) will check if container  exists in `redis` to bypass lookup in sds if it is unavailable.
> CH: Optimize directory objects

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/common.sh
- tests/functional/s3-marker.sh
- tests/unit/common/middleware/test_container_hierarchy.py
When a marker got a d1/object (with / delimiter), the d1/ was
skipped due to invalid check in marker management.
> CH: fix invalid use of marker

- oioswift/utils.py
Map these exceptions to 503 errors to tell the client to retry at a slower pace.
> Handle DeadlineReached exceptions from ObjectStorageApi

- oioswift/proxy/controllers/obj.py
The commit f5e484a25613f29dd2d799d16fa8cd735d2bf4b0 implemented a global mechanism to intercept `DeadlineReached` exceptions. This commit ensures these exceptions reach the appropriate handler, and are not considered as dummy `ClientException`.
> Handle more DeadlineReached exceptions from ObjectStorageApi

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/run-s3-tests.sh
- The CH v3 with '-' in prefix was improperly tested in lua
- Always use a versioned listing before removing a redis entry
- Conversion script may fails as it may use v3 keys when await v1 keys
> Various CH fixes

- oioswift/common/middleware/container_hierarchy.py
- tests/functional/run-s3-tests.sh
- tests/functional/s3-mpu.py
The behavior is not the same as we may want only upload-id or parts already done for a specifiq upload-iq.
A test was also added to ignore '-' as `base64.b64decode` ignores them when trying.
Note:
we should add metadata from `swift3` to identify properly related requests to MPU
> Distinguish list-multipart-uploads and list-parts requests

- oioswift/common/middleware/container_hierarchy.py
- oioswift/proxy/controllers/obj.py
When handling an object creation operation, and when the container supposed to host the object is missing, an unhandled exception was raised. This exception is now converted to a proper response error.
Also rename things and write documentation.
> Report missing container when checking versioning mode

- oioswift/proxy/controllers/account.py
- oioswift/proxy/controllers/container.py
- oioswift/proxy/controllers/obj.py
- oioswift/utils.py
The request ID header name was sometimes passed with an uppercase `X`, sometimes with lowercase. Now we import the proper header name from `oio` API.
> Properly pass request ID to oio API

- oioswift/proxy/controllers/account.py
- tests/functional/buckets-listing.sh
- tests/functional/encryption-tests.sh
- tests/functional/s3-acl-metadata.sh
- tests/functional/s3-conversion-container-hierarchy.sh
- tests/functional/s3-versioning-container-hierarchy.sh
- tests/functional/s3-versioning.sh
- tests/functional/s3_container_hierarchy_v2.sh
When Container Hierarchy is used, a lot of containers
may be created. This patch will use first character of
encoded delimiter of Container Hierarchy as delimiter.
Since S3 doesn't support delimiter in bucket listing (and
results are not compliant with bucket name for old SDS),
we also skip `subdir` entries when generating results
(thanks to @AymericDu ), it will no require SDS update
> Optimize bucket listing

- conf/default.cfg
- oioswift/common/middleware/container_hierarchy.py
- tests/functional/common.sh
- tests/functional/s3-versioning-container-hierarchy.sh
- tests/functional/s3_container_hierarchy_v2.sh
In some cases, there is no need to check if there is actually something in the container: the check is done when removing objects, and if a container is empty, it is removed from the prefix database.
> CH: do not discard "empty" prefixes

- .travis.yml
It is no more needed since oiozookeeper has been published on PyPI.
> CI: do not require system_site_packages

- oioswift/proxy/controllers/obj.py
- test-requirements.txt
As no versioning is involved in MPU or SLO, this commit will avoid useless request
> Do not enforce versioning of segments containers
